# Site settings
title: Diego Kiedanski's Blog 
description: "A minimal blog template, build with Jekyll."
author:
  name: "Diego Kiedanski"
  url: "www.danski.xyz"

personal:
  linkedin: "https://linkedin.com/in/diego-kiedanski"
  github: "https://github.com/gus0k"
  googlescholar: "https://scholar.google.com/citations?user=L1Qe4zgAAAAJ&hl=en"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: true
reverse: false
